# Generated by Django 5.2.17 on 2026-09-27 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('family_access', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_type', models.CharField(choices=[('todo', 'Zadanie'), ('calendar_event', 'Wydarzenie'), ('note', 'Notatka')], max_length=20, verbose_name='rodzaj')),
                ('content', models.TextField(verbose_name='treść')),
                ('date', models.DateField(blank=True, null=True, verbose_name='data')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='godzina')),
                ('school_item', models.CharField(blank=True, choices=[('homework', 'zadanie domowe'), ('class_test', 'praca klasowa'), ('test', 'sprawdzian'), ('quiz', 'kartkówka'), ('lucky_number', 'szczęśliwy numerek'), ('grade', 'ocena'), ('substitution', 'zastępstwo'), ('late_arrival', 'spóźnienie'), ('room_change', 'zmiana sali')], max_length=20, verbose_name='element szkolny')),
                ('source', models.CharField(choices=[('manual', 'Ręcznie'), ('eduvulcan', 'EduVulcan')], default='manual', max_length=20, verbose_name='źródło')),
                ('submission_key', models.UUIDField(blank=True, editable=False, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='utworzono')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='zmieniono')),
                ('assigned_member', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='assigned_entries', to='family_access.familymember', verbose_name='dla kogo')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_entries', to='family_access.familymember', verbose_name='dodane przez')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='family_access.family', verbose_name='rodzina')),
            ],
            options={
                'verbose_name': 'wpis',
                'verbose_name_plural': 'wpisy',
                'indexes': [models.Index(fields=['family', 'date'], name='entry_family_date_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('entry_type', 'calendar_event'), _negated=True), ('date__isnull', False), _connector='OR'), name='entry_calendar_event_requires_date')],
            },
        ),
    ]
