# Generated by Django 5.2.17 on 2026-09-27 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0001_initial'),
        ('family_access', '0002_automationtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='InboundNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_id', models.CharField(max_length=255, verbose_name='identyfikator powiadomienia')),
                ('title', models.CharField(max_length=255, verbose_name='tytuł')),
                ('message', models.TextField(verbose_name='treść')),
                ('captured_at', models.DateTimeField(verbose_name='przechwycono')),
                ('captured_date', models.DateField(verbose_name='dzień przechwycenia')),
                ('content_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField(verbose_name='dane źródłowe')),
                ('status', models.CharField(choices=[('pending', 'Oczekuje'), ('processing', 'Przetwarzanie'), ('processed', 'Przetworzone'), ('failed', 'Błąd')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('received_at', models.DateTimeField(auto_now_add=True, verbose_name='odebrano')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='przetworzono')),
                ('error', models.TextField(blank=True, verbose_name='błąd')),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inbound_notifications', to='family_access.family', verbose_name='rodzina')),
                ('token', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inbound_notifications', to='family_access.automationtoken', verbose_name='token')),
            ],
            options={
                'verbose_name': 'powiadomienie przychodzące',
                'verbose_name_plural': 'powiadomienia przychodzące',
                'constraints': [models.UniqueConstraint(fields=('family', 'notification_id'), name='inbound_unique_notification_id_per_family'), models.UniqueConstraint(fields=('family', 'content_hash', 'captured_date'), name='inbound_unique_content_per_family_day')],
            },
        ),
    ]
