# Generated by Django 5.2.17 on 2026-09-28 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0002_inboundnotification'),
        ('family_access', '0002_automationtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationConversionOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_index', models.PositiveSmallIntegerField(verbose_name='output index')),
                ('kind', models.CharField(choices=[('rule', 'Fixed rule'), ('rule_remainder', 'Unparsed rule remainder'), ('classification', 'Classification'), ('general_note', 'General note fallback')], max_length=20, verbose_name='kind')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'notification conversion output',
                'verbose_name_plural': 'notification conversion outputs',
                'ordering': ('notification', 'output_index'),
            },
        ),
        migrations.AddField(
            model_name='inboundnotification',
            name='attempt_count',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='attempt count'),
        ),
        migrations.AddField(
            model_name='inboundnotification',
            name='last_error_code',
            field=models.CharField(blank=True, max_length=64, verbose_name='last error code'),
        ),
        migrations.AddField(
            model_name='inboundnotification',
            name='lease_expires_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='lease expires at'),
        ),
        migrations.AddField(
            model_name='inboundnotification',
            name='next_attempt_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='next attempt at'),
        ),
        migrations.AddField(
            model_name='inboundnotification',
            name='raw_pruned_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='raw data pruned at'),
        ),
        migrations.AddIndex(
            model_name='inboundnotification',
            index=models.Index(fields=['status', 'next_attempt_at'], name='inbound_status_retry_idx'),
        ),
        migrations.AddIndex(
            model_name='inboundnotification',
            index=models.Index(fields=['status', 'lease_expires_at'], name='inbound_status_lease_idx'),
        ),
        migrations.AddConstraint(
            model_name='inboundnotification',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('lease_expires_at__isnull', False), ('status', 'processing')), models.Q(models.Q(('status', 'processing'), _negated=True), ('lease_expires_at__isnull', True)), _connector='OR'), name='inbound_lease_only_while_processing'),
        ),
        migrations.AddConstraint(
            model_name='inboundnotification',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'pending'), ('next_attempt_at__isnull', True), _connector='OR'), name='inbound_retry_only_while_pending'),
        ),
        migrations.AddConstraint(
            model_name='inboundnotification',
            constraint=models.CheckConstraint(condition=models.Q(('raw_pruned_at__isnull', True), models.Q(('message', ''), ('status', 'processed'), ('title', '')), _connector='OR'), name='inbound_prune_only_processed_raw_data'),
        ),
        migrations.AddField(
            model_name='notificationconversionoutput',
            name='entry',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversion_output', to='entries.entry', verbose_name='entry'),
        ),
        migrations.AddField(
            model_name='notificationconversionoutput',
            name='notification',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversion_outputs', to='entries.inboundnotification', verbose_name='notification'),
        ),
        migrations.AddConstraint(
            model_name='notificationconversionoutput',
            constraint=models.UniqueConstraint(fields=('notification', 'output_index'), name='conversion_output_unique_index_per_notification'),
        ),
        migrations.AddConstraint(
            model_name='notificationconversionoutput',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['rule', 'rule_remainder', 'classification', 'general_note'])), name='conversion_output_known_kind'),
        ),
    ]
