# Generated by Django 5.2.17 on 2026-09-28 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0003_notification_conversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversionWorkerHeartbeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, unique=True, verbose_name='name')),
                ('beat_at', models.DateTimeField(verbose_name='last heartbeat at')),
            ],
            options={
                'verbose_name': 'conversion worker heartbeat',
                'verbose_name_plural': 'conversion worker heartbeats',
            },
        ),
    ]
