# Generated by Django 5.2.17 on 2026-10-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entries', '0007_entry_school_subject'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='notificationconversionoutput',
            name='conversion_output_known_kind',
        ),
        migrations.AlterField(
            model_name='notificationconversionoutput',
            name='kind',
            field=models.CharField(choices=[('rule', 'Fixed rule'), ('rule_remainder', 'Unparsed rule remainder'), ('classification', 'Classification'), ('general_note', 'General note fallback'), ('duplicate', 'Duplicate of existing entry'), ('merged', 'Merged into existing entry')], max_length=20, verbose_name='kind'),
        ),
        migrations.AddConstraint(
            model_name='notificationconversionoutput',
            constraint=models.CheckConstraint(condition=models.Q(('kind__in', ['rule', 'rule_remainder', 'classification', 'general_note', 'duplicate', 'merged'])), name='conversion_output_known_kind'),
        ),
    ]
