# Generated by Django 5.2.17 on 2026-09-27 19:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_access', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutomationToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, verbose_name='nazwa')),
                ('prefix', models.CharField(editable=False, max_length=16, verbose_name='prefiks')),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='utworzono')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='wygasa')),
                ('revoked_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='unieważniono')),
                ('last_used_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='ostatnio użyty')),
                ('member', models.ForeignKey(limit_choices_to={'is_active': True, 'role': 'parent'}, on_delete=django.db.models.deletion.CASCADE, related_name='automation_tokens', to='family_access.familymember', verbose_name='rodzic')),
            ],
            options={
                'verbose_name': 'token automatyzacji',
                'verbose_name_plural': 'tokeny automatyzacji',
            },
        ),
    ]
