# Generated by Django 5.2.17 on 2026-10-04 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('family_access', '0002_automationtoken'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthCacheEntry',
            fields=[
                ('cache_key', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('value', models.TextField()),
                ('expires', models.DateTimeField(db_index=True, null=True)),
            ],
        ),
    ]
