# Generated by Django 5.2.17 on 2026-10-05 15:37

from django.conf import settings
from django.db import migrations, models
from django.db.models import Count


def forwards(apps, schema_editor):
    """Nothing to change: the old per-user constraint implies the new one."""


def refuse_rollback_with_multi_family_users(apps, schema_editor):
    """Stop the rollback before the per-user constraint is restored.

    Lists only user ids (never names or emails). The operator deactivates the
    extra memberships in Django admin and runs the rollback again.
    """
    FamilyMember = apps.get_model('family_access', 'FamilyMember')
    user_ids = sorted(
        FamilyMember.objects.filter(is_active=True)
        .values('user_id')
        .annotate(active=Count('pk'))
        .filter(active__gt=1)
        .values_list('user_id', flat=True)
    )
    if user_ids:
        raise RuntimeError(
            'Cannot restore one active membership per user: these user ids have '
            f'more than one active membership: {", ".join(map(str, user_ids))}. '
            'Deactivate the extra memberships in Django admin first.'
        )


class Migration(migrations.Migration):

    dependencies = [
        ('family_access', '0003_authcacheentry'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    # The guard runs last forwards, so it runs first on rollback.
    operations = [
        migrations.RemoveConstraint(
            model_name='familymember',
            name='unique_active_family_membership_per_user',
        ),
        migrations.AddConstraint(
            model_name='familymember',
            constraint=models.UniqueConstraint(
                condition=models.Q(('is_active', True)),
                fields=('user', 'family'),
                name='unique_active_membership_per_user_family',
                violation_error_message=(
                    'This user already has an active membership in this family.'
                ),
            ),
        ),
        migrations.RunPython(forwards, refuse_rollback_with_multi_family_users),
    ]
