"""
Django settings for family_notes project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.lower() in {'1', 'true', 'yes', 'on'}


def env_list(name, default=''):
    return [item.strip() for item in os.getenv(name, default).split(',') if item.strip()]


def env_number(name, default, cast=float):
    value = os.getenv(name)
    if value is None or not value.strip():
        return default
    try:
        return cast(value)
    except ValueError:
        # Name the variable only; never echo configured values.
        raise ImproperlyConfigured(f'{name} must be a number.') from None


def env_positive_int(name, default):
    """A whole number above zero; anything else stops startup (fail closed)."""
    value = env_number(name, default, cast=int)
    if value <= 0:
        raise ImproperlyConfigured(f'{name} must be a positive whole number.')
    return value


def env_positive_int_tuple(name, default):
    """Comma-separated positive whole numbers, e.g. ``60,300``."""
    raw = os.getenv(name)
    if raw is None or not raw.strip():
        return tuple(default)
    try:
        values = tuple(int(item) for item in env_list(name))
    except ValueError:
        values = ()
    if not values or any(value <= 0 for value in values):
        # Name the variable only; never echo configured values.
        raise ImproperlyConfigured(
            f'{name} must be a comma-separated list of positive whole numbers.'
        )
    return values


# Headroom the conversion lease keeps above the classification deadline, for
# the database work around one classification call.
EDUVULCAN_LEASE_MARGIN_SECONDS = 30


def validate_eduvulcan_worker_settings(
    *,
    heartbeat_seconds,
    heartbeat_max_age_seconds,
    lease_seconds,
    classification_deadline_seconds,
):
    """Reject worker timing that a healthy worker could never satisfy.

    The freshness window must exceed the heartbeat interval, and one attempt's
    lease must outlast the classification deadline plus
    ``EDUVULCAN_LEASE_MARGIN_SECONDS``, or slow classifications would lose
    their lease and their paid-for results. Messages name variables only.
    """
    if not heartbeat_max_age_seconds > heartbeat_seconds:
        raise ImproperlyConfigured(
            'EDUVULCAN_WORKER_HEARTBEAT_MAX_AGE_SECONDS must be greater than '
            'EDUVULCAN_WORKER_HEARTBEAT_SECONDS.'
        )
    if not lease_seconds >= classification_deadline_seconds + EDUVULCAN_LEASE_MARGIN_SECONDS:
        raise ImproperlyConfigured(
            'EDUVULCAN_CONVERSION_LEASE_SECONDS must be at least '
            f'CLASSIFICATION_DEADLINE_SECONDS plus {EDUVULCAN_LEASE_MARGIN_SECONDS} seconds.'
        )


# Empty means the request carries no reasoning parameter (non-reasoning models).
OPENAI_REASONING_EFFORTS = frozenset({'', 'none', 'minimal', 'low', 'medium', 'high'})


def validate_classification_settings(
    *,
    enabled,
    debug,
    api_key,
    model,
    deadline_seconds,
    attempt_timeout_seconds,
    max_retries,
    reasoning_effort='',
):
    """Fail closed on unsafe classification configuration.

    Error messages name variables only, never their values, so a failed
    startup cannot print the provider key.
    """
    if not deadline_seconds > 0:
        raise ImproperlyConfigured('CLASSIFICATION_DEADLINE_SECONDS must be positive.')
    if not 0 < attempt_timeout_seconds <= deadline_seconds:
        raise ImproperlyConfigured(
            'CLASSIFICATION_ATTEMPT_TIMEOUT_SECONDS must be positive and not exceed '
            'CLASSIFICATION_DEADLINE_SECONDS.'
        )
    if max_retries not in (0, 1):
        raise ImproperlyConfigured('CLASSIFICATION_MAX_RETRIES must be 0 or 1.')
    if reasoning_effort not in OPENAI_REASONING_EFFORTS:
        raise ImproperlyConfigured(
            'OPENAI_REASONING_EFFORT must be empty or one of: '
            f'{", ".join(sorted(OPENAI_REASONING_EFFORTS - {""}))}.'
        )

    # Development may enable the flag without provider settings; the backend
    # factory still refuses to build a provider client until all are present.
    if not enabled or debug:
        return
    missing = [
        variable
        for variable, present in (
            ('OPENAI_API_KEY', bool(api_key)),
            ('OPENAI_CLASSIFICATION_MODEL', bool(model)),
        )
        if not present
    ]
    if missing:
        raise ImproperlyConfigured(
            'CLASSIFICATION_ENABLED requires these settings when DJANGO_DEBUG is false: '
            f'{", ".join(missing)}.'
        )


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# This fallback is development-only. Production must set DJANGO_SECRET_KEY.
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-local-development-only')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', default=False)

ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,::1')
CSRF_TRUSTED_ORIGINS = env_list('DJANGO_CSRF_TRUSTED_ORIGINS')

if not DEBUG and 'DJANGO_SECRET_KEY' not in os.environ:
    raise ImproperlyConfigured('DJANGO_SECRET_KEY is required when DJANGO_DEBUG is false.')

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = env_bool('DJANGO_SECURE_SSL_REDIRECT', default=not DEBUG)
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_HSTS_SECONDS = int(os.getenv('DJANGO_SECURE_HSTS_SECONDS', '3600' if not DEBUG else '0'))

# Shared authentication state uses the existing application database.
# Development may opt in for rehearsals; production always uses durable state.
AUTH_DB_CACHE = not DEBUG or env_bool('DJANGO_AUTH_DB_CACHE', default=False)
CACHES = {'default': {
    'BACKEND': ('family_notes.auth_cache.DatabaseAuthCache' if AUTH_DB_CACHE else
                'django.core.cache.backends.locmem.LocMemCache'),
    'LOCATION': 'family-notes-auth',
    'KEY_PREFIX': 'family_notes_auth',
}}

ACCOUNT_RATE_LIMITS = {'login': '30/m/ip', 'login_failed': '10/m/ip,5/300s/key'}
# Local self-registration is closed; Google first sign-in still creates the user
# that a superuser then maps to a family member (family_access.auth_adapters).
ACCOUNT_ADAPTER = 'family_access.auth_adapters.ClosedSignupAccountAdapter'
SOCIALACCOUNT_ADAPTER = 'family_access.auth_adapters.ExternalSignInSocialAccountAdapter'
# nginx overwrites this header; direct runserver development uses REMOTE_ADDR.
ALLAUTH_TRUSTED_CLIENT_IP_HEADER = 'X-Real-IP' if not DEBUG else None


# Application definition

INSTALLED_APPS = [
    'family_notes.apps.FamilyNotesAdminConfig',
    'family_access.apps.FamilyAccessConfig',
    'entries.apps.EntriesConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'family_notes.auth_security.AuthCacheFailureMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'family_access.context.FamilyContextMiddleware',
    'family_access.notices.MembershipNoticeMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'family_notes.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'family_notes' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'family_access.context_processors.family_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'family_notes.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DB_ENGINE = os.getenv('DB_ENGINE', 'sqlite').lower()

if DB_ENGINE == 'sqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.getenv('DB_NAME', BASE_DIR / 'db.sqlite3'),
        }
    }
elif DB_ENGINE in {'postgres', 'postgresql'}:
    required_db_settings = ['DB_HOST', 'DB_PORT', 'DB_NAME', 'DB_USER', 'DB_PASSWORD']
    missing_db_settings = [name for name in required_db_settings if not os.getenv(name)]
    if missing_db_settings:
        raise ImproperlyConfigured(
            f'Missing PostgreSQL settings: {", ".join(missing_db_settings)}'
        )

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'HOST': os.environ['DB_HOST'],
            'PORT': os.environ['DB_PORT'],
            'NAME': os.environ['DB_NAME'],
            'USER': os.environ['DB_USER'],
            'PASSWORD': os.environ['DB_PASSWORD'],
            'CONN_MAX_AGE': 60,
        }
    }
    if db_sslmode := os.getenv('DB_SSLMODE'):
        DATABASES['default']['OPTIONS'] = {'sslmode': db_sslmode}
else:
    raise ImproperlyConfigured(
        f'Unsupported DB_ENGINE {DB_ENGINE!r}; use sqlite or postgresql.'
    )


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_URL = 'account_login'
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'

GOOGLE_OAUTH_CLIENT_ID = os.getenv('GOOGLE_OAUTH_CLIENT_ID', '')
GOOGLE_OAUTH_CLIENT_SECRET = os.getenv('GOOGLE_OAUTH_CLIENT_SECRET', '')

if not DEBUG and (not GOOGLE_OAUTH_CLIENT_ID or not GOOGLE_OAUTH_CLIENT_SECRET):
    raise ImproperlyConfigured(
        'GOOGLE_OAUTH_CLIENT_ID and GOOGLE_OAUTH_CLIENT_SECRET are required '
        'when DJANGO_DEBUG is false.'
    )

# Natural-language classification (OpenAI Responses API).
# store=False is sent on every request. It does not replace Zero Data
# Retention (ZDR), which is deferred until after the MVP; without ZDR OpenAI may
# retain API traffic for abuse monitoring.
CLASSIFICATION_ENABLED = env_bool('CLASSIFICATION_ENABLED', default=False)
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')
OPENAI_CLASSIFICATION_MODEL = os.getenv('OPENAI_CLASSIFICATION_MODEL', '')
# Reasoning models (e.g. gpt-5 family) count reasoning tokens against the
# output limit; a low effort keeps the structured answer inside it.
OPENAI_REASONING_EFFORT = os.getenv('OPENAI_REASONING_EFFORT', '').strip().lower()
CLASSIFICATION_DEADLINE_SECONDS = env_number('CLASSIFICATION_DEADLINE_SECONDS', 25.0)
CLASSIFICATION_ATTEMPT_TIMEOUT_SECONDS = env_number(
    'CLASSIFICATION_ATTEMPT_TIMEOUT_SECONDS', 10.0
)
CLASSIFICATION_MAX_RETRIES = env_number('CLASSIFICATION_MAX_RETRIES', 1, cast=int)

validate_classification_settings(
    enabled=CLASSIFICATION_ENABLED,
    debug=DEBUG,
    api_key=OPENAI_API_KEY,
    model=OPENAI_CLASSIFICATION_MODEL,
    deadline_seconds=CLASSIFICATION_DEADLINE_SECONDS,
    attempt_timeout_seconds=CLASSIFICATION_ATTEMPT_TIMEOUT_SECONDS,
    max_retries=CLASSIFICATION_MAX_RETRIES,
    reasoning_effort=OPENAI_REASONING_EFFORT,
)

# EduVulcan notification conversion (roadmap S-05).
# The worker runs inside each Gunicorn process and is started only by the
# post_worker_init hook in gunicorn.conf.py; tests, runserver, and management
# commands never start it. Deploy migrations with the worker disabled, then
# enable it once the new release is healthy.
EDUVULCAN_WORKER_ENABLED = env_bool('EDUVULCAN_WORKER_ENABLED', default=False)
# Seconds between database sweeps for pending, retry-due, and stale rows.
EDUVULCAN_CONVERSION_SWEEP_INTERVAL_SECONDS = env_positive_int(
    'EDUVULCAN_CONVERSION_SWEEP_INTERVAL_SECONDS', 60
)
EDUVULCAN_CONVERSION_BATCH_SIZE = env_positive_int('EDUVULCAN_CONVERSION_BATCH_SIZE', 50)
EDUVULCAN_CONVERSION_LEASE_SECONDS = env_positive_int('EDUVULCAN_CONVERSION_LEASE_SECONDS', 120)
EDUVULCAN_CONVERSION_MAX_ATTEMPTS = env_positive_int('EDUVULCAN_CONVERSION_MAX_ATTEMPTS', 3)
# Delay before attempt 2, attempt 3, ...; later attempts reuse the last value.
EDUVULCAN_CONVERSION_RETRY_DELAYS_SECONDS = env_positive_int_tuple(
    'EDUVULCAN_CONVERSION_RETRY_DELAYS_SECONDS', (60, 300)
)
EDUVULCAN_RAW_RETENTION_DAYS = env_positive_int('EDUVULCAN_RAW_RETENTION_DAYS', 90)
# Active workers record a heartbeat this often; /healthz/conversion/ reports
# "unavailable" when the newest heartbeat is older than the max age.
EDUVULCAN_WORKER_HEARTBEAT_SECONDS = env_positive_int('EDUVULCAN_WORKER_HEARTBEAT_SECONDS', 30)
EDUVULCAN_WORKER_HEARTBEAT_MAX_AGE_SECONDS = env_positive_int(
    'EDUVULCAN_WORKER_HEARTBEAT_MAX_AGE_SECONDS', 180
)

validate_eduvulcan_worker_settings(
    heartbeat_seconds=EDUVULCAN_WORKER_HEARTBEAT_SECONDS,
    heartbeat_max_age_seconds=EDUVULCAN_WORKER_HEARTBEAT_MAX_AGE_SECONDS,
    lease_seconds=EDUVULCAN_CONVERSION_LEASE_SECONDS,
    classification_deadline_seconds=CLASSIFICATION_DEADLINE_SECONDS,
)

# Identity of the running release. Heartbeats record it, and
# /healthz/conversion/ counts only heartbeats of this release. The fallback is
# the resolved project directory's name: deployed releases live in
# /srv/family-notes/releases/<RELEASE_ID> behind the ``current`` symlink, and
# BASE_DIR is resolved, so every process of one release shares the value.
FAMILY_NOTES_RELEASE_ID = os.getenv('FAMILY_NOTES_RELEASE_ID', '').strip() or BASE_DIR.name

# Logging: Django's defaults stay in place; the EduVulcan conversion logger
# additionally sends INFO (sweeps, processed rows, retries, requeues, pruning)
# to the console, which systemd forwards to journald. Its messages carry only
# IDs, counts, codes, and exception class names.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        # journald adds the timestamp; level and logger name make lines filterable.
        'plain': {'format': '%(levelname)s %(name)s %(message)s'},
    },
    'handlers': {
        'console': {'class': 'logging.StreamHandler', 'formatter': 'plain'},
    },
    # Every other logger (family_access, family_notes, django.security, ...)
    # reaches the console at WARNING. Django's defaults print only with DEBUG
    # on, and handler-less loggers would fall back to a bare stderr line.
    'root': {'handlers': ['console'], 'level': 'WARNING'},
    'loggers': {
        'entries.eduvulcan': {
            'handlers': ['console'],
            'level': 'INFO',
            'propagate': False,
        },
        # One content-free line per provider call (outcome, status, request id).
        # Printed through the root handler, so root-level capture (privacy
        # tests) still sees it and nothing is printed twice.
        'entries.classification': {
            'level': 'INFO',
            'propagate': True,
        },
        # Django's own INFO chatter stays out; its warnings (django.security:
        # CSRF failures, disallowed hosts) propagate to the root handler.
        'django': {'level': 'WARNING'},
        # Unhandled view exceptions (500s). Django's default prints these only
        # with DEBUG on; without this a production 500 leaves no traceback.
        # ERROR keeps routine 4xx warnings out. The traceback has no local
        # variables or POST data, but its last line is the exception message,
        # which for a database error can quote a column value.
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
    },
}

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': GOOGLE_OAUTH_CLIENT_ID,
            'secret': GOOGLE_OAUTH_CLIENT_SECRET,
            'key': '',
        },
        'SCOPE': ['profile', 'email'],
    }
}


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'pl'

TIME_ZONE = 'Europe/Warsaw'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATICFILES_DIRS = [BASE_DIR / 'family_notes' / 'static']
STATIC_ROOT = Path(os.getenv('DJANGO_STATIC_ROOT', BASE_DIR / 'staticfiles'))

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
