"""
Django settings for family_notes project.

Generated by 'django-admin startproject' using Django 5.2.17.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
load_dotenv(BASE_DIR / '.env')


def env_bool(name, default=False):
    value = os.getenv(name)
    if value is None:
        return default
    return value.lower() in {'1', 'true', 'yes', 'on'}


def env_list(name, default=''):
    return [item.strip() for item in os.getenv(name, default).split(',') if item.strip()]


def env_number(name, default, cast=float):
    value = os.getenv(name)
    if value is None or not value.strip():
        return default
    try:
        return cast(value)
    except ValueError:
        # Name the variable only; never echo configured values.
        raise ImproperlyConfigured(f'{name} must be a number.') from None


def validate_classification_settings(
    *,
    enabled,
    debug,
    api_key,
    model,
    zdr_attested,
    deadline_seconds,
    attempt_timeout_seconds,
    max_retries,
):
    """Fail closed on unsafe classification configuration.

    Error messages name variables only, never their values, so a failed
    startup cannot print the provider key.
    """
    if not deadline_seconds > 0:
        raise ImproperlyConfigured('CLASSIFICATION_DEADLINE_SECONDS must be positive.')
    if not 0 < attempt_timeout_seconds <= deadline_seconds:
        raise ImproperlyConfigured(
            'CLASSIFICATION_ATTEMPT_TIMEOUT_SECONDS must be positive and not exceed '
            'CLASSIFICATION_DEADLINE_SECONDS.'
        )
    if max_retries not in (0, 1):
        raise ImproperlyConfigured('CLASSIFICATION_MAX_RETRIES must be 0 or 1.')

    # Development may enable the flag without provider settings; the backend
    # factory still refuses to build a provider client until all are present.
    if not enabled or debug:
        return
    missing = [
        variable
        for variable, present in (
            ('OPENAI_API_KEY', bool(api_key)),
            ('OPENAI_CLASSIFICATION_MODEL', bool(model)),
            ('OPENAI_ZDR_ATTESTED', bool(zdr_attested)),
        )
        if not present
    ]
    if missing:
        raise ImproperlyConfigured(
            'CLASSIFICATION_ENABLED requires these settings when DJANGO_DEBUG is false: '
            f'{", ".join(missing)}.'
        )


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# This fallback is development-only. Production must set DJANGO_SECRET_KEY.
SECRET_KEY = os.getenv('DJANGO_SECRET_KEY', 'django-insecure-local-development-only')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_bool('DJANGO_DEBUG', default=False)

ALLOWED_HOSTS = env_list('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1,::1')
CSRF_TRUSTED_ORIGINS = env_list('DJANGO_CSRF_TRUSTED_ORIGINS')

if not DEBUG and 'DJANGO_SECRET_KEY' not in os.environ:
    raise ImproperlyConfigured('DJANGO_SECRET_KEY is required when DJANGO_DEBUG is false.')

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
SECURE_SSL_REDIRECT = env_bool('DJANGO_SECURE_SSL_REDIRECT', default=not DEBUG)
SESSION_COOKIE_SECURE = not DEBUG
CSRF_COOKIE_SECURE = not DEBUG
SECURE_HSTS_SECONDS = int(os.getenv('DJANGO_SECURE_HSTS_SECONDS', '3600' if not DEBUG else '0'))


# Application definition

INSTALLED_APPS = [
    'family_notes.apps.FamilyNotesAdminConfig',
    'family_access.apps.FamilyAccessConfig',
    'entries.apps.EntriesConfig',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'allauth',
    'allauth.account',
    'allauth.socialaccount',
    'allauth.socialaccount.providers.google',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'allauth.account.middleware.AccountMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'family_notes.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'family_notes' / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'family_notes.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DB_ENGINE = os.getenv('DB_ENGINE', 'sqlite').lower()

if DB_ENGINE == 'sqlite':
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.getenv('DB_NAME', BASE_DIR / 'db.sqlite3'),
        }
    }
elif DB_ENGINE in {'postgres', 'postgresql'}:
    required_db_settings = ['DB_HOST', 'DB_PORT', 'DB_NAME', 'DB_USER', 'DB_PASSWORD']
    missing_db_settings = [name for name in required_db_settings if not os.getenv(name)]
    if missing_db_settings:
        raise ImproperlyConfigured(
            f'Missing PostgreSQL settings: {", ".join(missing_db_settings)}'
        )

    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.postgresql',
            'HOST': os.environ['DB_HOST'],
            'PORT': os.environ['DB_PORT'],
            'NAME': os.environ['DB_NAME'],
            'USER': os.environ['DB_USER'],
            'PASSWORD': os.environ['DB_PASSWORD'],
            'CONN_MAX_AGE': 60,
        }
    }
    if db_sslmode := os.getenv('DB_SSLMODE'):
        DATABASES['default']['OPTIONS'] = {'sslmode': db_sslmode}
else:
    raise ImproperlyConfigured(
        f'Unsupported DB_ENGINE {DB_ENGINE!r}; use sqlite or postgresql.'
    )


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

AUTHENTICATION_BACKENDS = [
    'django.contrib.auth.backends.ModelBackend',
    'allauth.account.auth_backends.AuthenticationBackend',
]

LOGIN_URL = 'account_login'
LOGIN_REDIRECT_URL = '/account/'
LOGOUT_REDIRECT_URL = '/'

GOOGLE_OAUTH_CLIENT_ID = os.getenv('GOOGLE_OAUTH_CLIENT_ID', '')
GOOGLE_OAUTH_CLIENT_SECRET = os.getenv('GOOGLE_OAUTH_CLIENT_SECRET', '')

if not DEBUG and (not GOOGLE_OAUTH_CLIENT_ID or not GOOGLE_OAUTH_CLIENT_SECRET):
    raise ImproperlyConfigured(
        'GOOGLE_OAUTH_CLIENT_ID and GOOGLE_OAUTH_CLIENT_SECRET are required '
        'when DJANGO_DEBUG is false.'
    )

# Natural-language classification (OpenAI Responses API).
# store=False is sent on every request but does not replace Zero Data
# Retention: set OPENAI_ZDR_ATTESTED only after an operator confirms the
# production OpenAI project is approved and configured for ZDR.
CLASSIFICATION_ENABLED = env_bool('CLASSIFICATION_ENABLED', default=False)
OPENAI_API_KEY = os.getenv('OPENAI_API_KEY', '')
OPENAI_CLASSIFICATION_MODEL = os.getenv('OPENAI_CLASSIFICATION_MODEL', '')
OPENAI_ZDR_ATTESTED = env_bool('OPENAI_ZDR_ATTESTED', default=False)
CLASSIFICATION_DEADLINE_SECONDS = env_number('CLASSIFICATION_DEADLINE_SECONDS', 25.0)
CLASSIFICATION_ATTEMPT_TIMEOUT_SECONDS = env_number(
    'CLASSIFICATION_ATTEMPT_TIMEOUT_SECONDS', 10.0
)
CLASSIFICATION_MAX_RETRIES = env_number('CLASSIFICATION_MAX_RETRIES', 1, cast=int)

validate_classification_settings(
    enabled=CLASSIFICATION_ENABLED,
    debug=DEBUG,
    api_key=OPENAI_API_KEY,
    model=OPENAI_CLASSIFICATION_MODEL,
    zdr_attested=OPENAI_ZDR_ATTESTED,
    deadline_seconds=CLASSIFICATION_DEADLINE_SECONDS,
    attempt_timeout_seconds=CLASSIFICATION_ATTEMPT_TIMEOUT_SECONDS,
    max_retries=CLASSIFICATION_MAX_RETRIES,
)

SOCIALACCOUNT_PROVIDERS = {
    'google': {
        'APP': {
            'client_id': GOOGLE_OAUTH_CLIENT_ID,
            'secret': GOOGLE_OAUTH_CLIENT_SECRET,
            'key': '',
        },
        'SCOPE': ['profile', 'email'],
    }
}


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'
STATIC_ROOT = Path(os.getenv('DJANGO_STATIC_ROOT', BASE_DIR / 'staticfiles'))

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
